#!/bin/sh

# Make some system commands not require sudo.
for command in mount umount pacman updatedb su shutdown reboot ; do
	alias "$command=sudo $command"
done; unset command

# Note: Prefer to keep env vars in single quotes, so they are expanded
# when they're used, not when defined. See SC2139.

# Abbreviations
alias e='$EDITOR'
alias E='$GRAPHICAL_EDITOR'
alias g='git'
alias o='xdg-open'
alias p='pacman'
alias t='task'
alias z='zathura'
alias ka='killall'
alias py='python'
alias sql='sqlite3'

# Verbosity and common settings.
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -vI'
alias bc='bc -ql'
alias ls='ls --almost-all --human-readable --color=auto --group-directories-first'
# MacOS:
# alias ls='ls -A -h --color=auto'
alias rg='rg -i'
alias tp='trash-put --'
alias rsync='rsync -vrPlu'
alias mkd='mkdir -pv'
alias ffmpeg='ffmpeg -hide_banner'
alias shfmt='shfmt --indent 4 --binary-next-line --case-indent --space-redirects --write'

# Use colored output
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'

# Dev-oriented
alias mci='sudo make clean install'
alias tse='tsc --target es6'
alias jsonfmt='prettier --stdin-filepath f.json'
alias adbpac='adb shell cmd package list packages'
alias penv='source venv/bin/activate 2> /dev/null || source .venv/bin/activate 2> /dev/null'
alias pfr='pip freeze > requirements.txt'

# Rclone
alias rc='rclone --progress --exclude "No_Backup/**" --exclude ".git/" copy'
alias rcd='rclone --dry-run --progress --exclude "No_Backup/**" --exclude ".git/" copy'
alias rs='rclone --create-empty-src-dirs --track-renames --progress --exclude "No_Backup/**" --exclude ".git/" sync'
alias rsd='rclone --create-empty-src-dirs --track-renames --dry-run --progress --exclude "No_Backup/**" --exclude ".git/" sync'

# Taskwarrior
# TODO: use a similar approach to 'open_journal_entry' instead of
# only 'yesterday' and 'today'.
alias t-done-y='task end.after:yesterday end.before:today completed'
alias t-done-t='task end.after:today completed'

# YouTube
alias yt='yt-dlp'
alias ytt='yt --skip-download --write-thumbnail'
alias yts='mpv --slang=en --fs --ytdl-raw-options=ignore-config=,sub-lang=en,write-auto-sub='
alias yta='yt --extract-audio --format bestaudio/best'
alias ytap='yt --extract-audio --format bestaudio/best --yes-playlist -o "%(playlist_index)02d - %(title)s [%(id)s].%(ext)s"'

# General

# [F]ile [M]anager
# alias fm='$FILE_MANAGER'

# [P]ackage [M]anager
alias pm='yay'

# [J]ournal [E]ntry
alias je='journal_entry'

# [G]allery [D]ownload
alias gld='gallery-dl'
