[formatting]
align_entries         = true
array_auto_collapse   = false
column_width          = 80
indent_entries        = false
indent_string         = "    "
indent_tables         = true
reorder_arrays        = false
reorder_inline_tables = false
reorder_keys          = true
