# {{@@ header() @@}}

[font]
size = 11.0

[window]
opacity = 0.90

[window.padding]
x = 10
y = 10

# {%@@- if os == "windows" +@@%}
[general]
working_directory = "{{@@ env['HOME'].replace('\\', '\\\\') @@}}"

[terminal]
shell = { program = "C:\\Program Files\\Git\\bin\\bash.exe", args = ["--login", "-i"]}
# {%@@- endif @@%}
