#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Use a higher DPI for larger screens
xrandr \
	--output DisplayPort-2 --primary --mode 2560x1440 --pos 1920x0 --rotate normal \
	--output HDMI-A-0 --mode 1920x1080 --pos 0x400 --rotate normal

# Apply properties for devices whose name is duplicated
DEVICE_NAME="Razer Razer DeathAdder V2 X HyperSpeed"
PROPERTY="libinput Accel Speed"
VALUE=-1

# Get all matching device IDs
DEVICE_IDS=$(xinput list | grep "$DEVICE_NAME" | sed -n 's/.*id=\([0-9]\+\).*/\1/p')

# Apply the configuration for each ID
for ID in $DEVICE_IDS; do
    xinput --set-prop "$ID" "$PROPERTY" "$VALUE"
    if [ $? -eq 0 ]; then
        echo "Configuration applied for device ID: $ID"
    else
        echo "Failed to apply configuration for device ID: $ID" >&2
    fi
done

setbg  &
dwmblocks &
remapd &

# Uncomment to use Xresources colors/settings on startup
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}"/x11/xresources & xrdbpid=$!

autostart='xcompmgr dunst pipewire'

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

blugon -S 4700 & # Bluelight filter
unclutter --timeout 2 &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
